feat: push repo to github using pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,11 +1,51 @@
 stages:
+  - mirror
   - tests
   - pages
   - download_dependencies
   - build_sources
   - build_and_publish_docker_image
+  - release
+
+variables:
+  GITHUB_MIRROR_REPO: davidebianchi03/codebox
+
+default:
+  after_script:
+    # push the status of the pipeline of github 
+    # if this is the last job of the pipeline
+    - |
+      if [ -z $CI_COMMIT_TAG ]; then
+        if [ $CI_COMMIT_BRANCH = $CI_DEFAULT_BRANCH ]; then
+          if [ $CI_JOB_STATUS = "success" ] || [ $CI_JOB_STATUS = "failed" ]; then
+            gh_job_status=pending
+            if [ $CI_JOB_STATUS = "success" ]; then gh_job_status=success; fi
+            if [ $CI_JOB_STATUS = "failed" ]; then gh_job_status=failure; fi
+          
+            response=$(curl -s -w "\n%{http_code}" -X POST \
+              -H "Authorization: token $GITHUB_TOKEN" \
+              https://api.github.com/repos/$GITHUB_MIRROR_REPO/statuses/$CI_COMMIT_SHA \
+              -d "{
+                    \"state\": \"pending\",
+                    \"context\": \"GitLab CI\",
+                    \"target_url\": \"$CI_PIPELINE_URL\"
+                  }")
+
+            http_code=$(echo "$response" | tail -n1)
+            body=$(echo "$response" | head -n -1)
+                
+            if [ "$http_code" -ne 201 ]; then
+              echo "GitHub API request failed with HTTP code $http_code"
+              echo $http_code
+              exit 1
+            fi
+          fi
+        fi
+      fi
 
 include:
+  - local: .gitlab/ci/github_mirror.yml
+
   - local: .gitlab/ci/unit_tests.yml
 
   - local: .gitlab/ci/pages.yml
@@ -17,3 +57,5 @@ include:
   - local: .gitlab/ci/build_sources.yml
 
   - local: .gitlab/ci/build_and_publish_docker_image.yml
+
+  - local: .gitlab/ci/release.yml
